name: Deploy Backend to GCP VM

on:
  push:
    branches: [main]
    paths:
      - "backend/**" # Chỉ chạy khi có thay đổi trong thư mục backend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Backend via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USER }}
          key: ${{ secrets.GCP_KEY }}
          # Truyền DB connection string vào script
          env:
            DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
          script: |
            cd food-landing
            git pull origin main
            cd backend
            # Cập nhật DB string vào file service
            echo "Environment=\"DB_CONNECTION_STRING=${DB_CONNECTION_STRING}\"" | sudo tee -a /etc/systemd/system/food-backend.service > /dev/null
            /usr/local/go/bin/go build -o server
            sudo systemctl restart food-backend
