name: Deploy Frontend to GCP VM

on:
  push:
    branches: [main] # Chạy khi có push lên nhánh main
    paths:
      - "frontend/**" # Chỉ chạy khi có thay đổi trong thư mục frontend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Frontend via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USER }}
          key: ${{ secrets.GCP_KEY }}
          script: |
            cd food-landing
            git pull origin main
            cd frontend
            npm install
            npm run build
            sudo systemctl reload nginx
